CREATE TABLE IF NOT EXISTS sn_users (
   id BIGINT NOT NULL,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(100) NOT NULL,
   email VARCHAR(200) NOT NULL,
   password VARCHAR(300) NOT NULL,
   role VARCHAR(50) NOT NULL,
   PRIMARY KEY (id)
);